# Generated by Django 4.2.13 on 2024-10-15 15:16

import chat_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_message_id_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=chat_app.models.Message.get_time),
        ),
    ]
